### ISSUE TITLE
Package-specific extra tests

### ISSUE THREAD

**Issue by timholy** [JuliaRegistries/RegistryCI.jl#195] opened 2019-05-12 09:25 UTC
One feature of the old METADATA was that it ran tests for a random subset of dependent packages. Over at https://github.com/JuliaImages/Images.jl/issues/805, we've wondered about whether it would be possible to add extra tests in a package-specific manner. Perhaps an `ExtraTests.toml` file that would list other packages whose tests should be run using the proposed new version.

It would be extra compute burden for Travis, which is why I ask before thinking about implementation.

**Comment by DilumAluthge** [comment] 2020-01-05 23:44
I’m moving this issue to RegistryCI.jl since it seems to be a CI feature that would added to this package.

**Comment by DilumAluthge** [comment] 2020-03-07 02:09
Can I close this as a duplicate of #120?

**Comment by DilumAluthge** [comment] 2021-03-11 01:59
I'm closing this as a duplicate of #120

**Comment by DilumAluthge** [comment] 2021-03-11 01:59
Duplicate of #120

**Closed by DilumAluthge** 2021-03-11 01:59 UTC
Labels: enhancement
