### ISSUE TITLE
Julia compat check should consider the same major version

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/RegistryCI.jl#264] opened 2020-08-20 21:04 UTC
https://github.com/JuliaRegistries/General/pull/19630#issuecomment-674561423

**Comment by fredrikekre** [comment] 2020-08-20 21:10
Yes, transferred

**Comment by ericphanson** [comment] 2020-10-29 20:03
is this the same issue as https://github.com/JuliaRegistries/RegistryCI.jl/issues/180?

**Comment by DilumAluthge** [comment] 2020-11-19 08:47
I think so.

**Comment by DilumAluthge** [comment] 2021-03-12 12:12
I'm going to close this as a duplicate of #180.

**Comment by DilumAluthge** [comment] 2021-03-12 12:12
Duplicate of #180

**Closed by DilumAluthge** 2021-03-12 12:12 UTC
Labels: bug
