### ISSUE TITLE
Include VisualStringDistances.jl for CI

### ISSUE THREAD

**Issue by fredrikekre** [JuliaRegistries/RegistryCI.jl#273] opened 2020-10-08 16:34 UTC
We should include https://github.com/ericphanson/VisualStringDistances.jl in CI.

**Comment by DilumAluthge** [comment] 2020-10-09 10:53
Actually, duplicate of https://github.com/JuliaRegistries/RegistryCI.jl/issues/10?

**Closed** 2020-10-12 13:13 UTC
