### ISSUE TITLE
Failing to register for Julia 1.7 due to wrong version chosen for libblastrampoline_jll 

### ISSUE THREAD

**Issue by andreasvarga** [JuliaRegistries/RegistryCI.jl#480] opened 2022-09-18 10:13 UTC
This is a duplicate of  an issue formulated [20 hours ago](https://github.com/JuliaRegistries/General/issues/68456#issue-1376775903), in the hope that this is the _right place_ for this issue.

I tried to register a new version (0.4.2) of [PeriodicSystems.jl,](https://github.com/andreasvarga/PeriodicSystems.jl) only for Julia 1.7, but the registering procedure failed by tring to include a version of libblastrampoline_jll (5.1.1) which is intended to be used with Julia 1.8. Version 5.1.1 was  indicated as the _only possible version_ although in Project.toml libblastrampoline_jll = "3.0.4" is set in the dependencies together with Julia 1.7. The error message from the CI.log is:

```
[ Info: Attempting to `Pkg.add` package...
    Updating registry at `/tmp/jl_EcQ2LU/registries/General`
┌ Error: Some registries failed to update:
│     — `/tmp/jl_EcQ2LU/registries/General` — registry dirty
└ @ Pkg.Registry /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:449
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package libblastrampoline_jll [8e850b90]:
 libblastrampoline_jll [8e850b90] log:
 ├─possible versions are: 5.1.1 or uninstalled
 └─found to have no compatible versions left with PeriodicSystems [5decd0d0]
   └─PeriodicSystems [5decd0d0] log:
     ├─possible versions are: 0.1.0-0.4.2 or uninstalled
     └─restricted to versions 0.4.2 by an explicit requirement, leaving only versions 0.4.2
```

See [ CI.log](https://github.com/JuliaRegistries/General/actions/runs/3073464173/jobs/4965610363).

**Additional remark:** Due to an [issue](https://github.com/JuliaPackaging/Yggdrasil/issues/4969#issuecomment-1146836975) related to the impossibility to generate wrappers for the SLICOT library for Julia v1.8, I am forced to use version 1.7 for which all tests still pass. A PR has been proposed to fix this issue (unfortunately still waiting to be merged by an _authorized person_, see https://github.com/JuliaPackaging/Yggdrasil/pull/5259) . Even if merged, I am not sure if this PR will cure the situation.

**Comment by DilumAluthge** [comment] 2022-09-18 20:30
Duplicate of https://github.com/JuliaRegistries/General/issues/68456

**Closed by DilumAluthge** 2022-09-18 20:30 UTC
