### ISSUE TITLE
Automerge should check status of commit to ensure that all checks have been satisfied

### ISSUE THREAD

**Issue by kdheepak** [JuliaRegistries/RegistryCI.jl#123] opened 2019-12-04 21:11 UTC
Currently AutoMerge might merge a package that has failing tests.

**Comment by fredrikekre** [comment] 2019-12-04 21:14
IMO it is your (the package authors) responsibility not to release broken packages.

**Comment by kdheepak** [comment] 2019-12-04 21:19
Sure, but you can say something similar about checking for compat bounds of dependencies and version number increment suggestions, no?

**Comment by DilumAluthge** [comment] 2019-12-27 15:00
I’m realizing now that this is a duplicate of #120

**Closed by DilumAluthge** 2019-12-27 15:00 UTC
